packageExtensions:
  "guess-webpack@*":
    dependencies:
      memory-fs: "*"
      webpack-sources: "*"
  "theme-ui@*":
    peerDependencies:
      react: "^16.11.0"
  "@theme-ui/theme-provider@*":
    peerDependencies:
      react: "^16.11.0"
      "@theme-ui/css": "*"
  "rebass@*":
    peerDependencies:
      react: "^16.8.6"
  "@rebass/forms@*":
    dependencies:
      "@styled-system/should-forward-prop": "*"
    peerDependencies:
      react: "^16.8.6"
  "gatsby-plugin-intl3@*":
    peerDependencies:
      react: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.js
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-berry.js
