version: "3"
services:
  vor_app:
    build:
      context: .
      dockerfile: docker/vor/dev.dockerfile
    container_name: vor_app
    depends_on:
      - db
    environment:
      SITE_URL: https://localhost:8001
      DB_USERNAME: postgres
      DB_PASSWORD: developmentonly
      DB_HOST: vor-postgres
      DB_PORT: 5432
    # allow debugging
    security_opt:
      - "apparmor=unconfined"
    cap_add:
      - "SYS_PTRACE"
    volumes:
      - .:/usr/src/vor
    ports:
      - "40000:40000"
      - "8080:8080"

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/dev.dockerfile
    depends_on:
      - vor_app
    ports:
      - "8000:80"

  db:
    build:
      context: ./docker/postgres/
      dockerfile: dev.dockerfile
    container_name: vor-postgres
    environment:
      POSTGRES_PASSWORD: developmentonly
      POSTGRES_DB: defaultdb
    volumes:
      - vor:/var/lib/postgresql/data
#      - ./docker/postgres/ssl:/ssl
#      - ./docker/postgres/pga_hba.conf:/var/lib/postgresql/data/pga_hba.conf
#      - ./docker/postgres/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    ports:
      - "5432:5432"

volumes:
  ? vor
