version: "3"
services:
  app:
    build:
      context: .
      dockerfile: docker/vor/dev.dockerfile
    container_name: app
    depends_on:
      - db
    environment:
      SITE_URL: localhost
      DB_USERNAME: postgres
      DB_PASSWORD: developmentonly
      DB_HOST: vor-postgres
      DB_PORT: 5432
    # allow debugging
    security_opt:
      - "apparmor=unconfined"
    cap_add:
      - "SYS_PTRACE"
    volumes:
      - .:/usr/src/vor
    ports:
      - "40000:40000"
      - "8080:8080"

  db:
    image: postgres:11.5
    container_name: vor-postgres
    environment:
      POSTGRES_PASSWORD: developmentonly
      POSTGRES_DB: defaultdb
    volumes:
      - vor:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  ? vor
