## Docker Compose for development
version: "3"
services:
  vor_app:
    image: chrsep/go-devtools:latest
    container_name: vor_app
    working_dir: /src/vor
    depends_on:
      - db

    # Tell the container where to find the entry point to your app.
    environment:
      # go-devtools docker specific env
      SRC_ENTRYPOINT: /src/vor/pkg/*.go

      # vor specific env
      SITE_URL: localhost:8001
      DB_USERNAME: postgres
      DB_PASSWORD: developmentonly
      DB_HOST: vor-postgres
      DB_PORT: 5432
    # allow debugging
    security_opt:
      - "apparmor=unconfined"
    cap_add:
      - "SYS_PTRACE"
    volumes:
      - .:/src/vor
    ports:
      - "40000:40000"
      - "8080:8080"

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/dev.dockerfile
    depends_on:
      - vor_app
    ports:
      - "8000:80"

  db:
    build:
      context: ./docker/postgres/
      dockerfile: dev.dockerfile
    container_name: vor-postgres
    environment:
      POSTGRES_PASSWORD: developmentonly
      POSTGRES_DB: defaultdb
    volumes:
      - vor:/var/lib/postgresql/data
#      - ./docker/postgres/ssl:/ssl
#      - ./docker/postgres/pga_hba.conf:/var/lib/postgresql/data/pga_hba.conf
#      - ./docker/postgres/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    ports:
      - "5432:5432"

volumes:
  ? vor
