version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - run: |
          cd ./docker/postgres/ssl
          ./generate.sh
          cd ../../../
          docker-compose up -d
      - run: |
          cd frontend
          yarn install
          yarn build
          yarn cy:run
