version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - node-modules--{{ checksum "frontend/yarn.lock" }}
      - run: |
          echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
          echo ' [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      - run: |
          nvm install v12
          node -v
          nvm alias default v12
      - run: npm install -g yarn
      - run: |
          cd ./docker/postgres/ssl
          ./generate.sh
          cd ../../../
          docker-compose up -d
      - run: |
          cd frontend
          yarn install --frozen-lockfile
      - run: |
          cd frontend
          yarn build:cy
          yarn cy:run
      - store_artifacts:
          path:  ~/repo/frontend/cypress/videos
      - store_artifacts:
          path:  ~/repo/frontend/cypress/screenshots
      - save_cache:
          when: always
          name: Save Yarn Package Cache
          key: node-modules-{{ checksum "frontend/yarn.lock" }}
          paths:
            # Caching node_modules only is faster but might cause some build problems
            # when running different commands or different node/yarn version.
            # Cache .cache when troubles emerge.
            #- ~/.cache/yarn
            #- ~/.cache/Cypress
            - ./frontend/node_modules
