version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/repo
    steps:
      - checkout
      - run: docker-compose -f docker-compose.prod.yml up --build -d
