version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/repo
    steps:
      - checkout
      - run: |
          sudo apt update
          sudo apt install nodejs
          node -v
      - run: |
          curl -o- -L https://yarnpkg.com/install.sh | bash
      - run: |
          cd ./docker/postgres/ssl
          ./generate.sh
          cd ../../../
          docker-compose up -d
      - run: |
          cd frontend
          yarn install
          yarn build
          yarn cy:run
