version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-cypress-{{ checksum "frontend/yarn.lock" }}
      - run: |
          echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
          echo ' [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      - run: |
          nvm install v12
          node -v
          nvm alias default v12
      - run: npm install -g yarn wait-on
      - run: |
          cd ./docker/postgres/ssl
          ./generate.sh
          cd ../../../
          docker-compose up -d
      - run: |
          cd frontend
          yarn install --production --frozen-lockfile
      - run: |
          cd frontend
          yarn cy:ci
      - store_artifacts:
          path:  ~/repo/frontend/cypress/videos
      - store_artifacts:
          path:  ~/repo/frontend/cypress/screenshots
      - save_cache:
          when: always
          name: Save Yarn Package Cache
          key: yarn-cypress-{{ checksum "frontend/yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ~/.cache/Cypress
            - ./frontend/node_modules
